import { Issue } from "../types";

export const MOCK_ISSUES: Issue[] = [
  {
    module: "Auth",
    feature: "Google SSO",
    issueTitle: "SSO redirection loop on slow 3G network",
    issueDescription: "When logging in on a throttled mobile connection, the OAuth flow gets stuck in an infinite redirection loop between our callback page and Google's consent screen.",
    stepsToReproduce: "1. Enable 'Slow 3G' throttling in Chrome DevTools.\n2. Click 'Log in with Google'.\n3. Wait for the redirect back.",
    resources: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
    issueStatus: "IN PROGRESS",
    devComments: "Investigating token validation race condition. It seems the session cookie is not set before the callback page triggers a redirect.",
    estimation: "3h",
    assignedDate: "2026-05-22",
    assignee: "John Doe",
    resolutionDate: "",
    qaComments: "Reported by client in staging environment.",
    sheetSource: "App"
  },
  {
    module: "Payments",
    feature: "Stripe Checkout",
    issueTitle: "Stripe webhook payment status mismatch on subscription upgrades",
    issueDescription: "When a user upgrades their plan, the webhook is processed but fails to update the user account tier because of a database lock condition.",
    stepsToReproduce: "1. Create user account on Basic tier.\n2. Go to billing and select 'Upgrade to Pro'.\n3. Complete sandbox Stripe payment.",
    resources: "https://stripe.com/docs/api",
    issueStatus: "IN QA",
    devComments: "Lock resolved. Updated transaction isolation level to READ_COMMITTED. Ready for QA verification.",
    estimation: "5h",
    assignedDate: "2026-05-21",
    assignee: "Jane Smith",
    resolutionDate: "",
    qaComments: "Assigning to Alice for verification on sandbox environment.",
    sheetSource: "Admin"
  },
  {
    module: "Dashboard",
    feature: "Chart Zoom",
    issueTitle: "Recharts overlapping X-axis labels on mobile viewport",
    issueDescription: "On viewports smaller than 640px, the X-axis date labels overlap and become unreadable due to tight margins.",
    stepsToReproduce: "1. Open dashboard page.\n2. Shrink window to mobile width.\n3. Scroll down to Developer Workload distribution chart.",
    resources: "",
    issueStatus: "FIXED",
    devComments: "Added custom responsive formatter and auto-rotated the labels by 45 degrees when screen width is under 768px.",
    estimation: "1h",
    assignedDate: "2026-05-22",
    assignee: "Alice Johnson",
    resolutionDate: "2026-05-22",
    qaComments: "Fixed today. Will double check responsive scaling.",
    sheetSource: "App"
  },
  {
    module: "Settings",
    feature: "Dark Mode",
    issueTitle: "Dark mode toggling causes white screen flicker in browser",
    issueDescription: "When clicking the dark mode toggle, the theme classes are applied too late in the paint cycle, causing a brief white flash of the entire screen.",
    stepsToReproduce: "1. Clear local storage.\n2. Open app.\n3. Toggle dark mode back and forth rapidly.",
    resources: "",
    issueStatus: "TODO",
    devComments: "",
    estimation: "2h",
    assignedDate: "2026-05-22",
    assignee: "John Doe",
    resolutionDate: "",
    qaComments: "Reported by lead QA. Highly annoying on night shifts.",
    sheetSource: "App"
  },
  {
    module: "Notifications",
    feature: "Slack Hook",
    issueTitle: "Slack webhook fails to send tags for high-priority alerts",
    issueDescription: "High-priority alarms are successfully dispatched to Slack, but the channel mentions (@channel or user tags) fail to trigger notifications because they are sent as raw text instead of correctly escaped Slack blocks.",
    stepsToReproduce: "1. Trigger simulated critical database failure.\n2. Verify the payload dispatched to webhook.\n3. Check Slack channel for alerts.",
    resources: "https://api.slack.com/messaging/webhooks",
    issueStatus: "RESOLVED",
    devComments: "Fixed formatting of critical payloads. Tested with active slack webhook client. Confirmed tags now properly ping team members.",
    estimation: "2h",
    assignedDate: "2026-05-20",
    assignee: "Bob Lee",
    resolutionDate: "2026-05-22",
    qaComments: "Tested. Pings are working perfectly on the QA Slack sandbox.",
    sheetSource: "Admin"
  },
  {
    module: "Dashboard",
    feature: "Metrics KPI",
    issueTitle: "KPI Cards load infinite skeletons when API returns empty array",
    issueDescription: "If there are no issues found for a given query, instead of showing 0, the metric cards display loading skeletons indefinitely.",
    stepsToReproduce: "1. Apply a date filter where no issues are found.\n2. Observe KPI cards.",
    resources: "",
    issueStatus: "FIXED",
    devComments: "Added fallback for undefined/empty data arrays in hook handlers.",
    estimation: "1.5h",
    assignedDate: "2026-05-21",
    assignee: "Alice Johnson",
    resolutionDate: "2026-05-21",
    qaComments: "Confirmed resolved. Skeleton now hides immediately when API responds.",
    sheetSource: "Admin"
  },
  {
    module: "Auth",
    feature: "Sign Up",
    issueTitle: "Sign Up form password validator ignores special character rule",
    issueDescription: "The form validator claims password needs 1 special character, but users can sign up using only alphanumeric passwords.",
    stepsToReproduce: "1. Navigate to Sign Up page.\n2. Enter password 'P@ssword123'. Validator is green.\n3. Enter 'Password123' (no special char). Validator is STILL green.",
    resources: "",
    issueStatus: "IN PROGRESS",
    devComments: "Regex pattern in signup schema was missing the lookahead assertion.",
    estimation: "1h",
    assignedDate: "2026-05-22",
    assignee: "Bob Lee",
    resolutionDate: "",
    qaComments: "Critical security issue. Needs hotfix today.",
    sheetSource: "App"
  },
  {
    module: "Settings",
    feature: "Profile",
    issueTitle: "Avatar image uploading fails to crop on mobile screens",
    issueDescription: "On mobile screen heights, the crop overlay is cut off at the bottom and the crop buttons are unreachable, making profile picture updates impossible on iPhones.",
    stepsToReproduce: "1. Go to Profile Settings on iPhone.\n2. Select avatar upload.\n3. Try to hit crop/save.",
    resources: "",
    issueStatus: "NOT RESOLVED",
    devComments: "Mobile modal height is absolute instead of viewport-percentage. We need to refactor the dialog component layout.",
    estimation: "4h",
    assignedDate: "2026-05-19",
    assignee: "Jane Smith",
    resolutionDate: "",
    qaComments: "Still failing on iOS Safari. Reopened.",
    sheetSource: "App"
  },
  {
    module: "Payments",
    feature: "Invoice",
    issueTitle: "Invoice PDF download triggers 504 gateway timeout",
    issueDescription: "Generating large itemized invoice sheets triggers a server gateway timeout because puppeteer takes longer than 15 seconds to render the page.",
    stepsToReproduce: "1. Go to Billing History.\n2. Click download on an invoice with 50+ line items.\n3. Wait 15 seconds.",
    resources: "",
    issueStatus: "TODO",
    devComments: "",
    estimation: "8h",
    assignedDate: "2026-05-22",
    assignee: "Unassigned",
    resolutionDate: "",
    qaComments: "Customer reported multiple errors. High priority.",
    sheetSource: "Admin"
  },
  {
    module: "Notifications",
    feature: "Email",
    issueTitle: "Password reset email template breaks on Microsoft Outlook",
    issueDescription: "HTML email layout breaks completely inside Outlook's rendering engine. Content is squished, and the 'Reset Password' button is invisible.",
    stepsToReproduce: "1. Send a password reset email to an Outlook address.\n2. View email inside Microsoft Outlook desktop client.",
    resources: "",
    issueStatus: "IN QA",
    devComments: "Replaced grid-based template with standard nested tables. Tested in Litmus with 10+ versions of Outlook. Layout is now solid.",
    estimation: "4h",
    assignedDate: "2026-05-18",
    assignee: "John Doe",
    resolutionDate: "",
    qaComments: "Sent test email to sandbox. Pending verification.",
    sheetSource: "Admin"
  }
];
